# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_trend_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='first_spotted_at',
        ),
    ]
