# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_auto_20180628_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
