# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0007_auto_20180628_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='last_spotted_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
