# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0008_trend_last_spotted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='last_spotted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
